# Generated by Django 5.1.3 on 2024-12-04 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lead', '0004_lead_lead_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CLient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_consultant', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('deliverable_type', models.CharField(max_length=255)),
                ('deliverable_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('prospecting', 'Prospecting'), ('contacted', 'Contacted'), ('proposal_sent', 'Proposal Sent'), ('active', 'Active'), ('on_hold', 'On Hold'), ('delivered', 'Delivered'), ('post_delivery_follow_up', 'Post Delivery Follow Up'), ('closed_successful', 'Closed Successful'), ('closed_unsuccessful', 'Closed Unsuccessful')], default='inactive', max_length=30)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('next_followup', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_companies', to='lead.lead')),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_contact_persons', to='lead.lead')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
