# Generated by Django 5.1.3 on 2024-12-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='comment',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='user',
            new_name='employee',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='overtime_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('leave', 'Leave')], max_length=10),
        ),
    ]
