# Generated by Django 5.1.3 on 2024-12-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0002_rename_comment_attendance_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='overtime_hours',
        ),
        migrations.AddField(
            model_name='attendance',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('full_day', 'Full Day'), ('half_day', 'Half Day'), ('leave', 'Leave')], max_length=10),
        ),
    ]
