# Generated by Django 5.1.3 on 2024-11-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_lead_linkedin_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
